version: '3.5'
services:
  db:
    image: "postgres:${POSTGRES_TAG}"
    restart: always
    expose:
      - "5432"
    #    ports:
    #      - "5555:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Use local volume to be able to restore it just in case
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  backend:
    container_name: "rest_messenger"
    build:
      context: ./rest_messenger
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:${SERVER_PORT}'
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - SECRET_KEY
      - DEBUG
