# Generated by Django 3.0.5 on 2020-04-13 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='tmp', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e6d144e0-1f80-4832-ac40-7a998077e211'), editable=False, primary_key=True, serialize=False),
        ),
    ]
